### ISSUE TITLE
Finish migration to the new repository

### ISSUE THREAD

**Issue by stevenremot** [hoaproject/Contributions-Emacs-Pp#1]
There are still some things to do to finish moving this package from my personal repository to this one.

First, the version included in this repository is not up to date. We should **take the last version from my repository**, which also has auto-indentation.

Then, the **readme** from the old repo needs to be **adapted** and **inserted** in the new one.

We can also **talk about the license**. I used the GPL license because it seems good for an Emacs package targeted to end-users, but if there is a preferred license for Hoa sub-projects I don't mind changing it.

After the codebase has been updated, we will have to **prepare for registration in MELPA**. [MELPA](https://github.com/milkypostman/melpa) is an archive for Emacs packages. You can register your package on it by providing the github repository. Each time there is a commit on master, MELPA detects it, and update the package in its archive.

As the master branch of some packages can be unstable, there is another archive, MELPA stable, that looks if new version tags have been created in the package's repository so that the package maintainer can control the releases.

I started to write version tags in my personal repository. Should we keep doing it? If I understand correctly, Hoa projects use a continuous delivery system, So I suppose every push to master must be stable.

In any case, we will have to **register the new package's repository in MELPA**. It is done by addressing a pull request to the MELPA repository.

And finally, when the PR to MELPA is accepted, I just have to **close my personal repo** and the migration will be over \o/

Do you have any thoughts about this plan?

**Comment by Hywan** [comment]
- Latest version from your repository: Of course!
- `README.md` need to be updated: Of course yes!
- About the license, yes we have [this license](http://hoa-project.net/LICENSE), [linked in the `README.md` file](https://github.com/hoaproject/Contributions-Emacs-Pp#license),
- MELPA: OK with it, ok for the `master`, ok for tags. Yes we use a rolling-release based approach for the `Central` (set of all libraries) but not necessarily for all contributions. We adapt ourselves to the culture of the project in which we contribute to. So it's up to you to decide what is the best approach.

Can't be much more agree with your plan. Go!

**Comment by stevenremot** [comment]
Okay, thanks for the answer! Once my pull request is accepted I will create the tag "v0.2.1" to be synchronized with the old repo.

**Comment by Hywan** [comment]
I have updated the copyright license: https://github.com/hoaproject/Contributions-Emacs-Pp/commit/91d882b2c9277d14e2681363c8622d189ee60ac5.
I have also compressed the PNG: https://github.com/hoaproject/Contributions-Emacs-Pp/commit/724b0abff232375df6131ed261f1181fe5539c7b.

**Comment by Hywan** [comment]
Feel free to close this issue if needed.

**Comment by stevenremot** [comment]
I added the version tag. Do not hesitate to tell me if the format does not suit your conventions.

I still have to update the repository on MELPA. I'm not sure whether I should make it point to the github repository or the "private" one. It will be fetched regularly by MELPA, so it may be better to use the github one?

**Comment by Hywan** [comment]
The tag format must not follow our conventions but the ones of Emacs' world in this particular case. We don't want people to learn something new, they just want to use their tools and extensions as they used to.

For the link, point to Github. Yes this is a mirror but with a higher uptime than us. We must ensure a high reliability and Github is more likely to have a better one than us ;-).

**Comment by Hywan** [comment]
Could you also write a Github release in addition to the tag? It helps for the communication.

Bonus: A changelog? If you have time only. Not necessary.

**Comment by stevenremot** [comment]
The MELPA recipe has been updated and my personal repository is closed. The migration is over!

**Comment by Hywan** [comment]
Perfect! Thank you :-).
